version: 2.1

commands:
  setup_aws_access:
    steps:
      - run:
          name: Setting AWS Credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV

terraform_jobs: &terraform_jobs
  docker:
    - image: hashicorp/terraform:0.12.24

clojure_jobs: &clojure_jobs
  docker:
    - image: circleci/clojure:openjdk-14-lein-2.9.1-buster

jobs:
  terraform:
    <<: *terraform_jobs
    steps:
    - checkout
    - setup_aws_access
    - run:
        name: Terraform Init
        command: terraform init
    - run:
        name: Terraform Apply
        command: terraform apply -auto-aprove

  test:
    <<: *clojure_jobs
    steps:
    - checkout
    - run:
        command: cd lscc_raffler && lein test

  build:
    <<: *clojure_jobs
    steps:
    - checkout
    - run:
        command: cd lscc_raffler && lein uberjar

workflows:
  deploy_dev:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

  deploy_prod:
    jobs:
      - terraform:
          context: aws-playground
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master

