version: 2.1

commands:
  setup_aws_access:
    steps:
      - run:
          name: Setting AWS Credentials
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV

terraform_jobs: &terraform_jobs
  docker:
    - image: hashicorp/terraform:0.12.24

clojure_jobs: &clojure_jobs
  docker:
    - image: circleci/clojure:openjdk-14-lein-2.9.1-buster

jobs:
  terraform:
    <<: *terraform_jobs
    parameters:
      environment:
        description: The environment where this will run
        type: string
    steps:
    - checkout
    - setup_aws_access
    - run:
        name: Terraform Init
        working_directory: infrastructure/environments/<<parameters.environment>>
        command: terraform init
    - run:
        name: Terraform Apply
        working_directory: infrastructure/environments/<<parameters.environment>>
        command: terraform apply -auto-approve

  test:
    <<: *clojure_jobs
    steps:
    - checkout
    - run:
        working_directory: lscc_raffler
        command: lein test

  build:
    <<: *clojure_jobs
    steps:
    - checkout
    - run:
        working_directory: lscc_raffler
        command: lein uberjar

workflows:
  deploy_dev:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

  deploy_prod:
    jobs:
      - test:
          filters:
            branches:
              only: master

      - build:
          requires:
            - test

      - terraform:
          environment: dev
          context: aws-playground
          requires:
            - build
