version: 2.1

terraform_jobs: &terraform_jobs
  docker:
    - image: hashicorp/terraform:0.12.24

clojure_jobs: &clojure_jobs
  docker:
    - image: circleci/clojure:openjdk-14-lein-2.9.1-buster

jobs:
  terraform:
    <<: *terraform_jobs
    steps:
    - checkout
    - run:
        name: Terraform Init
        command: terraform init
    - run:
        name: Terraform Apply
        command: terraform apply -auto-aprove

  test:
    <<: *clojure_jobs
    steps:
    - checkout
    - run:
        command: cd lscc_raffler && lein test

  build:
    <<: *clojure_jobs
    steps:
    - checkout
    - run:
        command: cd lscc_raffler && lein uberjar

workflows:
  deploy_dev:
    jobs:
      - test:
          filters:
            branches:
              ignore: master

  deploy_prod:
    jobs:
      - test:
          filters:
            branches:
              only: master
